
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    depends_on:
      - backend
    env_file:
      - .env 
    networks:
      - voice-transcription_network

  backend:
    build:
      context: ./voice-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./voice-backend:/app
      - whisper_model_data:/app/models
    env_file:
      - .env  
    networks:
      - voice-transcription_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 

volumes:
  whisper_model_data:

networks:
  voice-transcription_network:
    driver: bridge